
# Spring related settings
server:
  port: 9090
  servlet:
    session:
      timeout: 3m
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SMARTBUY?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 123qwerty
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      shutdown-timeout: 30s

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false

      #open-in-view: false
      #properties:
    # hibernate.format_sql: true
# logging level
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.ust: DEBUG
    #org.hibernate.SQL: info
    #org.hibernate.type.descriptor.sql: trace